# https://gohugo.io/getting-started/configuration/

baseURL = "https://openpracticelibrary.com/"
languageCode = "en-us"
title = "Open Practice Library"
theme = "casper"
enableGitInfo = true


[params]
paginatedsections = ["practice"]
logo = "images/logo.svg"
description = "Practices that empower teams to collaborate and deliver iteratively"
hideHUGOSupport = true
googleAnalyticsUserID = "UA-111461618-1"

customCSS = [
  "css/custom.css",
  "https://fonts.googleapis.com/css?family=Arimo:400,700"
]

[permalinks]
page = "/:slug/"

[[menu.main]]
name = "Perspectives"
weight = 3
identifier = "Perspectives"
url = "/perspective/"

[[menu.main]]
name = "GitHub"
weight = 2
identifier = "GitHub"
url = "https://github.com/openpracticelibrary/openpracticelibrary"

[[menu.main]]
name = "Gitter"
weight = 1
identifier = "Gitter"
url = "https://gitter.im/openpracticelibrary/"

[[menu.main]]
name = "What's New"
weight = 0
identifier = "What's New"
url = "https://github.com/openpracticelibrary/openpracticelibrary/pulls?q=is%3Apr+is%3Aclosed+base%3Amaster"
