backend:
  name: git-gateway
  repo: openpracticelibrary/openpracticelibrary
  branch: master

# local_backend: true

publish_mode: editorial_workflow
media_folder: "static/images" # Media files will be stored in the repo under images/uploads
public_folder: "/images" # The src attribute for uploaded media will begin with /images/uploads
slug:
  encoding: "ascii"
  clean_accents: true
  sanitize_replacements: "-"
collections:
  - name: "practice" # Used in routes, e.g., /admin/collections/blog
    label: "Practice" # Used in the UI
    publish: false
    folder: "src/pages/practice" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - label: "Template Key"
        name: "templateKey"
        widget: "hidden"
        default: "practice-page"
        required: true
      - label: "Title of practice"
        hint: "The name of the practice"
        name: "title"
        widget: "string"
      - label: "Objective"
        hint: "One liner main objective for the practice"
        name: "subtitle"
        widget: "string"
      - label: "Publish Date"
        name: "date"
        widget: "datetime"
      - label: "Authors"
        hint: "Comma-separated list of LOWER CASE github usernames eg., springdo, rdebeasi, tdbeattie"
        name: "authors"
        widget: "list"
        default: []
      - label: "Tags"
        hint: "Where does this practice live on the Library Loop?"
        name: tags
        widget: "select"
        multiple: true
        required: false
        max: 3
        options:
          - label: "Validate (Discovery Loop)"
            value: "validate"
          - label: "Value (Discovery Loop)"
            value: "value"
          - label: "Culture (Foundation)"
            value: "culture"
          - label: "Methods (Foundation)"
            value: "methods"
          - label: "Ideate (Options Pivot)"
            value: "ideate"
          - label: "Insight (Options Pivot)"
            value: "insight"
          - label: "Measure (Delivery Loop)"
            value: "measure"
          - label: "Learn (Delivery Loop)"
            value: "learn"
      - label: "Mobius Loop Tag"
        hint: "Where does this practice live on the Mobius Loop?"
        name: mobiusTag
        widget: "select"
        multiple: false
        required: true
        options:
          - label: "Discovery"
            value: "discovery"
          - label: "Delivery"
            value: "delivery"
          - label: "Foundation"
            value: "foundation"
          - label: "Options"
            value: "options"
      - label: "Cover Image"
        name: "icon"
        hint: "Image to be used on the home screen and cards for the practice"
        widget: "image"
        required: true
        default: "https://github.com/openpracticelibrary/opl-media/blob/master/images/Needs%20an%20Image.png?raw=true"
      - label: 'What is this practice?'
        name: 'whatIs'
        widget: 'markdown'
      - label: 'Why do this practice?'
        name: 'whyDo'
        widget: 'markdown'
      - label: 'How do I execute this practice?'
        name: 'howTo'
        widget: 'markdown'
      - label: 'Media Gallery'
        name: 'mediaGallery'
        widget: "list"
        fields:
          - label: "Media Link"
            name: link
            widget: string
      - label: 'Links we love'
        name: 'resources'
        widget: "list"
        fields:
          - label: "Link"
            name: link
            widget: string
          - label: "Link Type"
            name: "linkType"
            widget: "select"
            options:
              - label: "web"
                value: "web"
              - label: "purchase"
                value: "purchase"
              - label: "podcast"
                value: "podcast"
              - label: "video"
                value: "video"
          - label: "Description"
            name: "description"
            widget: "string"
      - label: "No. of people required"
        hint: "How many people are needed for the practice eg 2+ or 10"
        name: "people"
        widget: "string"
        required: false
      - label: "Time length"
        hint: "How long is needed to facilitate this practice"
        name: "time"
        widget: "string"
        required: false
      - label: "Facilitation difficulty"
        hint: "How difficult is it to facilitate this practice"
        name: "difficulty"
        widget: "select"
        required: false
        options:
          - label: "Easy"
            value: "easy"
          - label: "Moderate"
            value: "moderate"
          - label: "Hard"
            value: "hard"
      - label: "Expected participants"
        hint: "Who should attend when running this practice? eg., The Team, The Product Owner, BAs"
        name: "participants"
        required: false
        widget: "list"
        default: []
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    publish: false
    folder: "src/pages/blog" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - label: "Template Key"
        name: "templateKey"
        widget: "hidden"
        default: "blog-page"
        required: true
      - label: "Title"
        hint: "The name of the perspective"
        name: "title"
        widget: "string"
      - label: "Subtitle"
        hint: "Catchy one liner for the perspective"
        name: "subtitle"
        widget: "string"
      - label: "Publish Date"
        name: "date"
        widget: "datetime"
      - label: "Authors"
        hint: "Comma-separated list of github usernames eg., springdo, rdebeasi, tdbeattie"
        name: "authors"
        widget: "list"
        default: []
      - label: "Jumbotron image"
        hint: "Large full width image for under the titles"
        name: "jumbotron"
        widget: "image"
        required: true
      - label: "Jumbotron alt text"
        hint: "Accessible description of the image for screen readers"
        name: "jumbotronAlt"
        widget: "string"
        required: false
      - label: "Body"
        name: "body"
        widget: "markdown"
        default: "## What is it? \n\n## Why use it? \n\n## Further Information\n\n"
  - name: "page" # Used in routes, e.g., /admin/collections/blog
    label: "Page" # Used in the UI
    publish: false
    folder: "src/pages/page" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - label: "Title"
        name: "title"
        widget: "string"
      - label: "Authors"
        name: "authors"
        widget: "list"
        default: []
      - label: "Publish Date"
        name: "date"
        widget: "datetime"
      - label: "Menu"
        name: "menu"
        widget: "select"
        required: false
        options:
          - label: "True"
            value: "main"
          - label: "False"
            value: ""
      - label: "Menu weight"
        name: "weight"
        widget: "string"
        required: false
        pattern: ["^[0-9]", "Must be a number between one and 9"]
      - label: "Body"
        name: "body"
        widget: "markdown"
  - name: "author" # Used in routes, e.g., /admin/collections/blog
    label: "Author" # Used in the UI
    format: "json"
    publish: false
    extension: "json"
    folder: "src/data/author" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{github}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - label: "Name"
        hint: "Your full name to be displayed on an article"
        name: "title"
        widget: "string"
      - label: "GitHub Username"
        hint: "Your github username"
        name: "github"
        widget: "string"
      - label: "About you"
        hint: "Short description of you"
        name: "bio"
        widget: "text"
        required: false
        pattern: [".{0,120}", "Must have at least 120 characters"]
      - label: "Location"
        hint: "Where are you based"
        name: "location"
        widget: "string"
        required: false
      - label: "WebSite"
        hint: "Your personal blog or website"
        name: "website"
        widget: "string"
        required: false
