backend:
  name: git-gateway
  repo: openpracticelibrary/openpracticelibrary
  branch: master # Branch to update (optional; defaults to master)

publish_mode: editorial_workflow
media_folder: "static/images" # Media files will be stored in the repo under images/uploads
public_folder: "/images" # The src attribute for uploaded media will begin with /images/uploads
collections:
  - name: "practice" # Used in routes, e.g., /admin/collections/blog
    label: "Practices" # Used in the UI
    folder: "content/practice" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Title of practice", name: "title", widget: "string"}
      - {label: "Subtitle", name: "subtitle", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Authors", name: "authors", widget: "list", default: []}
      - {label: "Area of the Mobius Loop", name: "area", widget: "select", options:
          [{label: "Discovery - Why", value: "discovery-loop-why"},
          {label: "Discovery - Outcomes", value: "discovery-loop-outcomes"},
          {label: "Options", value: "options"},
          {label: "Delivery - Deliver", value: "delivery-deliver"},
          {label: "Delivery - Measure & Learn", value: "delivery-measure-and-learn"},
          {label: "Foundation - Culture & Collaboration", value: "foundation-culture-and-collaboration"},
          {label: "Foundation - Technical", "foundation-technical"}]}
      - {label: "Tile icon", name: "icon", widget: "image", required: false}
      - {label: "Jumbotron image", name: "jumbotron", widget: "image", required: false}
      - {label: "Jumbotron alt text", name: "jumbotronAlt", widget: "string", required: false}
      - {label: "No. of people required", name: "people", widget: "string", required: false}
      - {label: "Time length", name: "time", widget: "string", required: false}
      - {label: "Facilitation difficulty", name: "difficulty", widget: "select", required: false, options:
          [{label: "Easy", value: "easy"},
          {label: "Moderate", value: "moderate"},
          {label: "Hard", value: "hard"}]}
      - {label: "Expected participants", name: "participants", required: false, widget: "list", default: []}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "page" # Used in routes, e.g., /admin/collections/blog
    label: "Pages" # Used in the UI
    folder: "content/page" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Authors", name: "authors", widget: "list", default: []}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Menu", name: "menu", widget: "select", required: false, options:
          [{label: "True", value: "main"},
          {label: "False", value: ""}]}
      - {label: "Menu weight", name: "weight", widget: "string", required: false, pattern: ["^[0-9]", "Must be a number between one and 9"]}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "author" # Used in routes, e.g., /admin/collections/blog
    label: "Authors" # Used in the UI
    format: "toml"
    extension: "toml"
    folder: "data/content/author" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{github}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Name", name: "title", widget: "string"}
      - {label: "GitHub Username", name: "github", widget: "string"}
      - {label: "About you", name: "bio", widget: "text", required: false, pattern: [".{0,120}", "Must have at least 120 characters"]}
      - {label: "Location", name: "location", widget: "string", required: false}
      - {label: "WebSite", name: "website", widget: "string", required: false}
